

about :

  name : "wArraySparse"
  description : "Collection of routines to operate effectively sparse array. A sparse array is an vector of intervals which splits number space into two subsets, internal and external. ArraySparse leverage iterating, inverting, minimizing and other operations on a sparse array. Use the module to increase memory efficiency of your algorithms."
  version : "0.3.34"
  enabled : 1
  interpreters :
  - nodejs >= 6.0.0
  - chrome >= 60.0.0
  - firefox >= 60.0.0
  keywords :
  - wTools

execution :

  scripts :
    test : wtest .run proto/**
    docgen : wdocgen staging

path :

  repository : git+https:///github.com/Wandalen/wArraySparse.git
  bugs : https:///github.com/Wandalen/wArraySparse/issues

step :

  export.proto :
    inherit : module.export
    export : path::proto
    tar : 0
    criterion :
      debug : 1
      proto : 1

build :

  proto.export :
    criterion :
      default : 1
      debug : 1
      raw : 1
      proto : 1
      export : 1
      tar : 1
      public : 1
    steps :
      - build::debug.raw
      - step::export.proto

